version: '2'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=local
    volumes:
      # live-reloading files
      - ./bin:/usr/src/app/bin
      - ./config:/usr/src/app/config
      - ./data:/usr/src/app/data
      - ./public:/usr/src/app/public
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./index.js:/usr/src/app/index.js
      - ./ecosystem.json:/usr/src/app/ecosystem.json
      - ./package.json:/usr/src/app/package.json
